name: spectrum
description: Library providing the common components of the ZX Spectrum.
version: 0.9.0
author: Tim Sneath <tim@sneath.org>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: "^0.12.29+1"